/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.main.sts.dto;

public class Duration {
	@org.codehaus.jackson.annotate.JsonProperty("value")
	private java.lang.Integer value;

 	public void setValue(java.lang.Integer value) {
		this.value = value;
	}

	public java.lang.Integer getValue() {
		return value;
	}

	@org.codehaus.jackson.annotate.JsonProperty("text")
	private java.lang.String text;

 	public void setText(java.lang.String text) {
		this.text = text;
	}

	public java.lang.String getText() {
		return text;
	}

}