/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.main.sts.dto;

public class ElementElement {
	@org.codehaus.jackson.annotate.JsonProperty("distance")
	private Distance distance;

 	public void setDistance(Distance distance) {
		this.distance = distance;
	}

	public Distance getDistance() {
		return distance;
	}

	@org.codehaus.jackson.annotate.JsonProperty("duration")
	private Duration duration;

 	public void setDuration(Duration duration) {
		this.duration = duration;
	}

	public Duration getDuration() {
		return duration;
	}

	@org.codehaus.jackson.annotate.JsonProperty("status")
	private java.lang.String status;

 	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.lang.String getStatus() {
		return status;
	}

}