/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.main.sts.dto;

public class RowElement {
	@org.codehaus.jackson.annotate.JsonProperty("elements")
	private ElementElement[] elements;

 	public void setElements(ElementElement[] elements) {
		this.elements = elements;
	}

	public ElementElement[] getElements() {
		return elements;
	}

}